# Generated by Django 2.1 on 2019-07-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjecttable',
            name='subjectsum',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
    ]
