# Generated by Django 2.1 on 2019-07-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlweb', '0002_auto_20190704_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjecttable',
            name='subjectname',
            field=models.CharField(max_length=40),
        ),
    ]
