# Generated by Django 2.1 on 2019-07-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlweb', '0004_auto_20190704_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjecttable',
            name='subjectsum',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
    ]
